# BookShelf/docker-compose.yml

version: '3.8' 

services:
  # 1. Veritabanı Servisi
  db:
    image: postgres:16-alpine 
    container_name: bookshelf_db 
    restart: unless-stopped 
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: shelf_scanner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  # 2. Backend Servisi
  backend:
    build: ./shelf-scanner-backend # Backend Dockerfile'ının olduğu klasör
    container_name: bookshelf_backend
    restart: unless-stopped
    ports:
      - "3001:3001" # Host:Container
    depends_on:
      - db 
    environment:
      NODE_ENV: production  
      DB_USER: postgres
      DB_HOST: db 
      DB_DATABASE: shelf_scanner
      DB_PASSWORD: admin
      DB_PORT: 5432
      OPENAI_API_KEY: ${OPENAI_API_KEY} 

  # 3. Frontend Servisi
  frontend:
    build: ./shelf-scanner-frontend 
    container_name: bookshelf_frontend
    restart: unless-stopped
    ports:
      - "5173:80" 
    depends_on:
      - backend 

volumes:
  postgres_data: